#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require __DIR__ . '/vendor/autoload.php';

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

$dotenv = new Dotenv\Dotenv(__DIR__, '.env');
$dotenv->load();

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/config/common/bootstrap.php';
require __DIR__ . '/config/console/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/config/common/main.php',
    require __DIR__ . '/config/console/main.php'
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
